### ISSUE TITLE
Public Code？

### ISSUE THREAD

**Issue by ZhikangNiu** [ictnlp/CTC-S2UT#1]
Thanks for your meaningful work and when will release the code？

**Comment by Poeroz** [comment]
Hello! I sincerely apologize for the delay in organizing the code for this project due to my busy schedule. I will sort it out and make it available as soon as possible. If it's very urgent, feel free to contact me via email, and I can provide you with some core module implementations. Once again, I deeply apologize for the inconvenience.

**Comment by ZhikangNiu** [comment]
Thanks!
